---
- name: OpenBSD Setup Playbook
  hosts: OpenBSD
  become: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2, ansible requires it
      raw: test -e /usr/local/bin/python2 || (pkg_add -I python-2.7.18p0)
      register: output
      changed_when: output.stdout != ""
      tags: always

  vars_files:
    - vars/common_vars.yml

  tasks:
    - include: tasks/openbsd/builder-package-install.yml
    - include: tasks/jenkins-builder-setup.yml
    - include: tasks/openbsd/swarm-client-install.yml
